set -x

wget https://download.pytorch.org/models/alexnet-owt-7be5be79.pth
wget https://download.pytorch.org/models/convnext_tiny-983f1562.pth
wget https://download.pytorch.org/models/convnext_small-0c510722.pth
wget https://download.pytorch.org/models/convnext_base-6075fbad.pth
wget https://download.pytorch.org/models/convnext_large-ea097f82.pth
wget https://download.pytorch.org/models/densenet121-a639ec97.pth
wget https://download.pytorch.org/models/densenet161-8d451a50.pth
wget https://download.pytorch.org/models/densenet169-b2777c0a.pth
wget https://download.pytorch.org/models/densenet201-c1103571.pth
wget https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
wget https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_v2_coco-dd69338a.pth
wget https://download.pytorch.org/models/fasterrcnn_mobilenet_v3_large_fpn-fb6a3cc7.pth
wget https://download.pytorch.org/models/fasterrcnn_mobilenet_v3_large_320_fpn-907ea3f9.pth
wget https://download.pytorch.org/models/fcos_resnet50_fpn_coco-99b0c9b7.pth
wget https://download.pytorch.org/models/keypointrcnn_resnet50_fpn_coco-9f466800.pth
wget https://download.pytorch.org/models/keypointrcnn_resnet50_fpn_coco-fc266e95.pth
wget https://download.pytorch.org/models/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth
wget https://download.pytorch.org/models/maskrcnn_resnet50_fpn_v2_coco-73cbd019.pth
wget https://download.pytorch.org/models/retinanet_resnet50_fpn_coco-eeacb38b.pth
wget https://download.pytorch.org/models/retinanet_resnet50_fpn_v2_coco-5905b1c5.pth
wget https://download.pytorch.org/models/ssd300_vgg16_coco-b556d3b4.pth
wget https://download.pytorch.org/models/ssdlite320_mobilenet_v3_large_coco-a79551df.pth
wget https://download.pytorch.org/models/efficientnet_b0_rwightman-3dd342df.pth
wget https://download.pytorch.org/models/efficientnet_b1_rwightman-533bc792.pth
wget https://download.pytorch.org/models/efficientnet_b1-c27df63c.pth
wget https://download.pytorch.org/models/efficientnet_b2_rwightman-bcdf34b7.pth
wget https://download.pytorch.org/models/efficientnet_b3_rwightman-cf984f9c.pth
wget https://download.pytorch.org/models/efficientnet_b4_rwightman-7eb33cd5.pth
wget https://download.pytorch.org/models/efficientnet_b5_lukemelas-b6417697.pth
wget https://download.pytorch.org/models/efficientnet_b6_lukemelas-c76e70fd.pth
wget https://download.pytorch.org/models/efficientnet_b7_lukemelas-dcc49843.pth
wget https://download.pytorch.org/models/efficientnet_v2_s-dd5fe13b.pth
wget https://download.pytorch.org/models/efficientnet_v2_m-dc08266a.pth
wget https://download.pytorch.org/models/efficientnet_v2_l-59c71312.pth
wget https://download.pytorch.org/models/googlenet-1378be20.pth
wget https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth
wget https://download.pytorch.org/models/maxvit_t-bc5ab103.pth
wget https://download.pytorch.org/models/mnasnet0.5_top1_67.823-3ffadce67e.pth
wget https://download.pytorch.org/models/mnasnet0_75-7090bc5f.pth
wget https://download.pytorch.org/models/mnasnet1.0_top1_73.512-f206786ef8.pth
wget https://download.pytorch.org/models/mnasnet1_3-a4c69d6f.pth
wget https://download.pytorch.org/models/mobilenet_v2-b0353104.pth
wget https://download.pytorch.org/models/mobilenet_v2-7ebf99e0.pth
wget https://download.pytorch.org/models/mobilenet_v3_large-8738ca79.pth
wget https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth
wget https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth
wget https://download.pytorch.org/models/raft_large_C_T_V1-22a6c225.pth
wget https://download.pytorch.org/models/raft_large_C_T_V2-1bb1363a.pth
wget https://download.pytorch.org/models/raft_large_C_T_SKHT_V1-0b8c9e55.pth
wget https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth
wget https://download.pytorch.org/models/raft_large_C_T_SKHT_K_V1-4a6a5039.pth
wget https://download.pytorch.org/models/raft_large_C_T_SKHT_K_V2-b5c70766.pth
wget https://download.pytorch.org/models/raft_small_C_T_V1-ad48884c.pth
wget https://download.pytorch.org/models/raft_small_C_T_V2-01064c6d.pth
wget https://download.pytorch.org/models/quantized/googlenet_fbgemm-c00238cf.pth
wget https://download.pytorch.org/models/quantized/inception_v3_google_fbgemm-71447a44.pth
wget https://download.pytorch.org/models/quantized/mobilenet_v2_qnnpack_37f702c5.pth
wget https://download.pytorch.org/models/quantized/mobilenet_v3_large_qnnpack-5bcacf28.pth
wget https://download.pytorch.org/models/quantized/resnet18_fbgemm_16fa66dd.pth
wget https://download.pytorch.org/models/quantized/resnet50_fbgemm_bf931d71.pth
wget https://download.pytorch.org/models/quantized/resnet50_fbgemm-23753f79.pth
wget https://download.pytorch.org/models/quantized/resnext101_32x8_fbgemm_09835ccf.pth
wget https://download.pytorch.org/models/quantized/resnext101_32x8_fbgemm-ee16d00c.pth
wget https://download.pytorch.org/models/quantized/resnext101_64x4d_fbgemm-605a1cb3.pth
wget https://download.pytorch.org/models/quantized/shufflenetv2_x0.5_fbgemm-00845098.pth
wget https://download.pytorch.org/models/quantized/shufflenetv2_x1_fbgemm-db332c57.pth
wget https://download.pytorch.org/models/quantized/shufflenetv2_x1_5_fbgemm-d7401f05.pth
wget https://download.pytorch.org/models/quantized/shufflenetv2_x2_0_fbgemm-5cac526c.pth
wget https://download.pytorch.org/models/regnet_y_400mf-c65dace8.pth
wget https://download.pytorch.org/models/regnet_y_400mf-e6988f5f.pth
wget https://download.pytorch.org/models/regnet_y_800mf-1b27b58c.pth
wget https://download.pytorch.org/models/regnet_y_800mf-58fc7688.pth
wget https://download.pytorch.org/models/regnet_y_1_6gf-b11a554e.pth
wget https://download.pytorch.org/models/regnet_y_1_6gf-0d7bc02a.pth
wget https://download.pytorch.org/models/regnet_y_3_2gf-b5a9779c.pth
wget https://download.pytorch.org/models/regnet_y_3_2gf-9180c971.pth
wget https://download.pytorch.org/models/regnet_y_8gf-d0d0e4a8.pth
wget https://download.pytorch.org/models/regnet_y_8gf-dc2b1b54.pth
wget https://download.pytorch.org/models/regnet_y_16gf-9e6ed7dd.pth
wget https://download.pytorch.org/models/regnet_y_16gf-3e4a00f9.pth
wget https://download.pytorch.org/models/regnet_y_16gf_swag-43afe44d.pth
wget https://download.pytorch.org/models/regnet_y_16gf_lc_swag-f3ec0043.pth
wget https://download.pytorch.org/models/regnet_y_32gf-4dee3f7a.pth
wget https://download.pytorch.org/models/regnet_y_32gf-8db6d4b5.pth
wget https://download.pytorch.org/models/regnet_y_32gf_swag-04fdfa75.pth
wget https://download.pytorch.org/models/regnet_y_32gf_lc_swag-e1583746.pth
wget https://download.pytorch.org/models/regnet_y_128gf_swag-c8ce3e52.pth
wget https://download.pytorch.org/models/regnet_y_128gf_lc_swag-cbe8ce12.pth
wget https://download.pytorch.org/models/regnet_x_400mf-adf1edd5.pth
wget https://download.pytorch.org/models/regnet_x_400mf-62229a5f.pth
wget https://download.pytorch.org/models/regnet_x_800mf-ad17e45c.pth
wget https://download.pytorch.org/models/regnet_x_800mf-94a99ebd.pth
wget https://download.pytorch.org/models/regnet_x_1_6gf-e3633e7f.pth
wget https://download.pytorch.org/models/regnet_x_1_6gf-a12f2b72.pth
wget https://download.pytorch.org/models/regnet_x_3_2gf-f342aeae.pth
wget https://download.pytorch.org/models/regnet_x_3_2gf-7071aa85.pth
wget https://download.pytorch.org/models/regnet_x_8gf-03ceed89.pth
wget https://download.pytorch.org/models/regnet_x_8gf-2b70d774.pth
wget https://download.pytorch.org/models/regnet_x_16gf-2007eb11.pth
wget https://download.pytorch.org/models/regnet_x_16gf-ba3796d7.pth
wget https://download.pytorch.org/models/regnet_x_32gf-9d47f8d0.pth
wget https://download.pytorch.org/models/regnet_x_32gf-6eb8fdc6.pth
wget https://download.pytorch.org/models/resnet18-f37072fd.pth
wget https://download.pytorch.org/models/resnet34-b627a593.pth
wget https://download.pytorch.org/models/resnet50-0676ba61.pth
wget https://download.pytorch.org/models/resnet50-11ad3fa6.pth
wget https://download.pytorch.org/models/resnet101-63fe2227.pth
wget https://download.pytorch.org/models/resnet101-cd907fc2.pth
wget https://download.pytorch.org/models/resnet152-394f9c45.pth
wget https://download.pytorch.org/models/resnet152-f82ba261.pth
wget https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth
wget https://download.pytorch.org/models/resnext50_32x4d-1a0047aa.pth
wget https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth
wget https://download.pytorch.org/models/resnext101_32x8d-110c445d.pth
wget https://download.pytorch.org/models/resnext101_64x4d-173b62eb.pth
wget https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth
wget https://download.pytorch.org/models/wide_resnet50_2-9ba9bcbe.pth
wget https://download.pytorch.org/models/wide_resnet101_2-32ee1156.pth
wget https://download.pytorch.org/models/wide_resnet101_2-d733dc28.pth
wget https://download.pytorch.org/models/deeplabv3_resnet50_coco-cd0a2569.pth
wget https://download.pytorch.org/models/deeplabv3_resnet101_coco-586e9e4e.pth
wget https://download.pytorch.org/models/deeplabv3_mobilenet_v3_large-fc3c493d.pth
wget https://download.pytorch.org/models/fcn_resnet50_coco-1167a1af.pth
wget https://download.pytorch.org/models/fcn_resnet101_coco-7ecb50ca.pth
wget https://download.pytorch.org/models/lraspp_mobilenet_v3_large-d234d4ea.pth
wget https://download.pytorch.org/models/shufflenetv2_x0.5-f707e7126e.pth
wget https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
wget https://download.pytorch.org/models/shufflenetv2_x1_5-3c479a10.pth
wget https://download.pytorch.org/models/shufflenetv2_x2_0-8be3c8ee.pth
wget https://download.pytorch.org/models/squeezenet1_0-b66bff10.pth
wget https://download.pytorch.org/models/squeezenet1_1-b8a52dc0.pth
wget https://download.pytorch.org/models/swin_t-704ceda3.pth
wget https://download.pytorch.org/models/swin_s-5e29d889.pth
wget https://download.pytorch.org/models/swin_b-68c6b09e.pth
wget https://download.pytorch.org/models/swin_v2_t-b137f0e2.pth
wget https://download.pytorch.org/models/swin_v2_s-637d8ceb.pth
wget https://download.pytorch.org/models/swin_v2_b-781e5279.pth
wget https://download.pytorch.org/models/vgg11-8a719046.pth
wget https://download.pytorch.org/models/vgg11_bn-6002323d.pth
wget https://download.pytorch.org/models/vgg13-19584684.pth
wget https://download.pytorch.org/models/vgg13_bn-abd245e5.pth
wget https://download.pytorch.org/models/vgg16-397923af.pth
wget https://download.pytorch.org/models/vgg16_features-amdegroot-88682ab5.pth
wget https://download.pytorch.org/models/vgg16_bn-6c64b313.pth
wget https://download.pytorch.org/models/vgg19-dcbb9e9d.pth
wget https://download.pytorch.org/models/vgg19_bn-c79401a0.pth
wget https://download.pytorch.org/models/mvit_v1_b-dbeb1030.pth
wget https://download.pytorch.org/models/mvit_v2_s-ae3be167.pth
wget https://download.pytorch.org/models/r3d_18-b3b3357e.pth
wget https://download.pytorch.org/models/mc3_18-a90a0ba3.pth
wget https://download.pytorch.org/models/r2plus1d_18-91a641e6.pth
wget https://download.pytorch.org/models/s3d-d76dad2f.pth
wget https://download.pytorch.org/models/swin3d_t-7615ae03.pth
wget https://download.pytorch.org/models/swin3d_s-da41c237.pth
wget https://download.pytorch.org/models/swin3d_b_1k-24f7c7c6.pth
wget https://download.pytorch.org/models/swin3d_b_22k-7c6ae6fa.pth
wget https://download.pytorch.org/models/vit_b_16-c867db91.pth
wget https://download.pytorch.org/models/vit_b_16_swag-9ac1b537.pth
wget https://download.pytorch.org/models/vit_b_16_lc_swag-4e70ced5.pth
wget https://download.pytorch.org/models/vit_b_32-d86f8d99.pth
wget https://download.pytorch.org/models/vit_l_16-852ce7e3.pth
wget https://download.pytorch.org/models/vit_l_16_swag-4f3808c9.pth
wget https://download.pytorch.org/models/vit_l_16_lc_swag-4d563306.pth
wget https://download.pytorch.org/models/vit_l_32-c7638314.pth
wget https://download.pytorch.org/models/vit_h_14_swag-80465313.pth
wget https://download.pytorch.org/models/vit_h_14_lc_swag-c1eb923e.pth
wget https://download.pytorch.org/models/crestereo-756c8b0f.pth
wget https://download.pytorch.org/models/crestereo-8f0e0e9a.pth
wget https://download.pytorch.org/models/crestereo-697c38f4.pth	
wget https://download.pytorch.org/models/raft_stereo_realtime-cf345ccb.pth
wget https://download.pytorch.org/models/raft_stereo_base_sceneflow-eff3f2e6.pth
wget https://download.pytorch.org/models/raft_stereo_base_middlebury-afa9d252.pth
wget https://download.pytorch.org/models/raft_stereo_base_eth3d-d4830f22.pth
